<?php

session_start();

const KEY = 'city-changer';
const DEFAULT_VALUE = 'Москва';
const DEFAULT_CONTEXT = 'web';

$context_prefix = [
    'zhbi' => 'zhbi-',
    'kip' => 'kip-',
    'pozharka' => 'pozhsnab-',
    'neft' => 'neft-',
    'svet' => 'svet-'
];
$find_context_prefix = isset($context_prefix[$modx->context->key]) ? $context_prefix[$modx->context->key] : '';

$cities = [
    'Москва' => 'moskva',
    'Одинцово' => 'odincovo',
    'Раменское' => 'ramenskoe',
    'Красногорск' => 'krasnogorsk',
    'Мытищи' => 'mytishchi',
    'Химки' => 'khimki',
    'Солнечногорск' => 'solnechnogorsk',
    'Дмитров' => 'dmitrov',
    'Балашиха' => 'balashiha',
    'Подольск' => 'podolsk',
    'Истра' => 'istra',
    'Чехов' => 'chekhov',
    'Сергиев Посад' => 'sergiev-posad',
    'Воскресенск' => 'voskresensk',
    'Наро-Фоминск' => 'naro-fominsk',
    'Ступино' => 'stupino',
    'Коломна' => 'kolomna',
    'Долгопрудный' => 'dolgoprudnyj',
    'Королёв' => 'korolyov',
    'Домодедово' => 'domodedovo',
    'Пушкино' => 'pushkino',
    'Серпухов' => 'serpuhov',
    'Клин' => 'klin',
    'Видное' => 'vidnoe',
    'Щёлково' => 'shchyolkovo',
    'Электросталь' => 'elektrostal',
    'Ногинск' => 'noginsk',
    'Егорьевск' => 'egorevsk',
    'Реутов' => 'reutov',
    'Жуковский' => 'zhukovskij',
    'Можайск' => 'mozhajsk',
    'Орехово-Зуево' => 'orekhovo-zuevo',
    'Лобня' => 'lobnya',
    'Волоколамск' => 'volokolamsk',
    'Дубна' => 'dubna',
    'Павловский Посад' => 'pavlovskij-posad',
    'Кашира' => 'kashira',
    'Лыткарино' => 'lytkarino',
    'Луховицы' => 'luhovicy',
    'Шатура' => 'shatura',
    'Фрязино' => 'fryazino',
    'Дзержинский' => 'dzerzhinskij',
    'Зарайск' => 'zarajsk',
    'Краснознаменск' => 'krasnoznamensk',
    'Руза' => 'ruza',
    'Черноголовка' => 'chernogolovka',
    'Бронницы' => 'bronnicy',
    'Лосино-Петровский' => 'losino-petrovskij',
    'Котельники' => 'kotelniki',
    'Талдом' => 'taldom',
    'Шаховская' => 'shahovskaya',
    'Власиха' => 'vlasiha',
    'Серебряные Пруды' => 'serebryanye-prudy',
    'Лотошино' => 'lotoshino',
    'Конаково' => 'konakovo',
    'Кольчугино' => 'kolchugino',
    'Киржач' => 'kirzhach',
    'Озёры' => 'ozyory',
    'Пущино' => 'pushchino',
    'Кубинка' => 'kubinka',
    'Кимры' => 'kimry',
    'Зеленоград' => 'zelenograd',
    'Обнинск' => 'obninsk',
    'Ермолино' => 'ermolino',
    'Тучково' => 'tuchkovo',
    'Звенигород' => 'zvenigorod',
    'Ивантеевка' => 'ivanteevka',
    'Электроугли' => 'elektrougli',
    'Железнодорожный' => 'zheleznodorozhnyj',
    'Щербинка' => 'shcherbinka',
    'Троицк' => 'troick',
    'Климовск' => 'klimovsk',
    'Апрелевка' => 'aprelevka',
    'Голицыно' => 'golicyno',
    'Нахабино' => 'nahabino',
    'Сходня' => 'skhodnya',
    'Селятино' => 'selyatino',
    'Верея' => 'vereya',
    'Куровское' => 'kurovskoe',
    'Ликино-Дулёво' => 'likino-dulyovo',
    'Электрогорск' => 'elektrogorsk',
    'Санкт-Петербург' => 'sankt-peterburg',
    'Волосово' => 'volosovo',
    'Волхов' => 'volkhov',
    'Всеволожск' => 'vsevolozhsk',
    'Выборг' => 'vyborg',
    'Гатчина' => 'gatchina',
    'Кингисепп' => 'kingisepp',
    'Кириши' => 'kirishi',
    'Кировск' => 'kirovsk',
    'Колпино' => 'kolpino',
    'Кронштадт' => 'kronshtadt',
    'Ломоносов' => 'lomonosov',
    'Луга' => 'luga',
    'Мурино' => 'murino',
    'Пушкин' => 'pushkin',
    'Сестрорецк' => 'sestroreczk',
    'Тихвин' => 'tikhvin',
    'Токсово' => 'toksovo',
    'Тосно' => 'tosno',
    'Краснодар' => 'krasnodar',
    'Анапа' => 'anapa',
    'Сочи' => 'sochi',
    'Новороссийск' => 'novorossiysk',
    'Лабинск' => 'labinsk',
    'Крымск' => 'krymsk',
    'Геленджик' => 'gelendzhik',
    'Майкоп' => 'maykop',
    'Армавир' => 'armavir',
    'Белореченск' => 'belorechensk',
    'Ейск' => 'eysk',
    'Славянск на Кубани' => 'slavyansk-na-kubani',
    'Тимашевск' => 'timashevsk',
    'Темрюк' => 'temryuk',
    'Горячий Ключ' => 'goryachiy-klyuch',
    'Туапсе' => 'tuapse',
    'Афипский' => 'afipsky',
    'Кореновск' => 'korenovsk',
    'Кропоткин' => 'kropotkin',
    'Абинск' => 'abinsk',
    'Курганинск' => 'kurganinsk',
    'Усть-Лабинск' => 'ust-labinsk',
    'Апшеронск' => 'apsheronsk',
    'станица Северская' => 'stanitsa-severskaya',
    'Псков' => 'pskov',
    'Великие Луки' => 'velikie-luki',
    'Великий Новгород' => 'velikij-novgorod',
    'Боровичи' => 'borovichi',
    'Петрозаводск' => 'petrozavodsk',
    'Мурманск' => 'murmansk',
    'Апатиты' => 'apatity',
    'Заполярный' => 'zapolyarnyj',
    'Кандалакша' => 'kandalaksha',
    'Кировск' => 'spb-kirovsk',
    'Ковдор' => 'kovdor',
    'Мончегорск' => 'monchegorsk',
    'Оленегорск' => 'olenegorsk',
    'Нижний Новгород' => 'Nizhny-Novgorod',
    'Арзамас' => 'arzamas',
    'Балахна' => 'balakhna',
    'Бор' => 'bor',
    'Выкса' => 'vyksa',
    'Дзержинск' => 'dzerzhinsk',
    'Новосибирск' => 'novosibirsk',
    'Бердск' => 'berdsk',
    'Искитим' => 'iskitim',
    'Обь' => 'ob',
    'Екатеринбург' => 'yekaterinburg',
    'Артёмовский' => 'artyomovsky',
    'Берёзовский' => 'beryozovsky',
    'Верхняя Пышма' => 'verkhnyaya-pyshma',
    'Каменск-Уральский' => 'kamensk-uralsky',
    'Кушва' => 'kushva',
    'Новоуральск' => 'novouralsk',
    'Первоуральск' => 'pervouralsk',
    'Серов' => 'serov',
    'Тюмень' => 'tyumen',
    'Красноярск' => 'krasnoyarsk',
    'Ачинск' => 'achinsk',
    'Железногорск' => 'zheleznogorsk',
    'Канск' => 'kansk',
    'Лесосибирск' => 'lesosibirsk',
    'Минусинск' => 'minusinsk',
    'Назарово' => 'nazarovo',
    'Норильск' => 'norilsk',
    'Сосновоборск' => 'sosnovoborsk',
    'Челябинск' => 'chelyabinsk',
    'Златоуст' => 'zlatoust',
    'Копейск' => 'kopeysk',
    'Магнитогорск' => 'magnitogorsk',
    'Миасс' => 'miass',
    'Самара' => 'samara',
    'Тольятти' => 'tolyatti',
    'Сызрань' => 'syzran',
    'Новокуйбышевск' => 'novokuybyshevsk',
    'Ростов-на-Дону' => 'rostov-na-donu',
    'Таганрог' => 'taganrog',
    'Шахты' => 'shakhty',
    'Новочеркасск' => 'novocherkassk',
    'Волгодонск' => 'volgodonsk',
    'Батайск' => 'bataisk',
    'Новошахтинск' => 'novoshakhtinsk',
    'Омск' => 'omsk',
    'Калачинск' => 'kalachinsk',
    'Исилькуль' => 'isilkul',
    'Называевск' => 'nazyvaevsk',
    'Тюкалинск' => 'tyukalinsk',
    'Воронеж' => 'voronezh',
    'Борисоглебск' => 'borisoglebsk',
    'Лиски' => 'liski',
    'Россошь' => 'rossosh',
    'Пермь' => 'perm',
    'Березники' => 'berezniki',
    'Краснокамск' => 'krasnokamsk',
    'Кудымкар' => 'kudymkar',
    'Кунгур' => 'kungur',
    'Лысьва' => 'lysva',
    'Соликамск' => 'solikamsk',
    'Чайковский' => 'chaikovsky',
    'Чусовой' => 'chusovoy',
    'Волгоград' => 'volgograd',
    'Волжский' => 'volzhsky',
    'Камышин' => 'kamyshin',
    'Белгород' => 'belgorod',
    'Старый Оскол' => 'stary-oskol',
    'Брянск' => 'bryansk',
    'Владимир' => 'vladimir',
    'Иваново' => 'ivanovo',
    'Калуга' => 'kaluga',
    'Кострома' => 'kostroma',
    'Курск' => 'kursk',
    'Липецк' => 'lipetsk',
    'Орёл' => 'oryol',
    'Рязань' => 'ryazan',
    'Смоленск' => 'smolensk',
    'Тамбов' => 'tambov',
    'Тверь' => 'tver',
    'Тула' => 'tula',
    'Новомосковск' => 'novomoskovsk',
    'Ярославль' => 'yaroslavl',
    'Архангельск' => 'arkhangelsk',
    'Северодвинск' => 'severodvinsk',
    'Вологда' => 'vologda',
    'Череповец' => 'cherepovets',
    'Калининград' => 'kaliningrad',
    'Сыктывкар' => 'syktyvkar',
    'Астрахань' => 'astrakhan',
    'Ставрополь' => 'stavropol',
    'Пятигорск' => 'pyatigorsk',
    'Саратов' => 'saratov',
    'Энгельс' => 'engels',
    'Балаково' => 'balakovo',
    'Пенза' => 'penza',
    'Ульяновск' => 'ulyanovsk',
    'Димитровград' => 'dimitrovgrad',
    'Оренбург' => 'orenburg',
    'Орск' => 'orsk',
    'Курган' => 'kurgan',
    'Томск' => 'tomsk',
    'Северск' => 'seversk',
    'Кемерово' => 'kemerovo',
    'Новокузнецк' => 'novokuznetsk',
    'Прокопьевск' => 'prokopyevsk',
    'Междуреченск' => 'mezhdurechensk',
    'Иркутск' => 'irkutsk',
    'Братск' => 'bratsk',
    'Ангарск' => 'angarsk',
    'Усть-Илимск' => 'ust-ilimsk',
    'Улан-Удэ' => 'ulan-ude',
    'Барнаул' => 'barnaul',
    'Бийск' => 'biysk',
    'Рубцовск' => 'rubtsovsk',
    'Владивосток' => 'vladivostok',
    'Уссурийск' => 'ussuriysk',
    'Находка' => 'nakhodka',
    'Хабаровск' => 'khabarovsk',
    'Комсомольск-на-Амуре' => 'komsomolsk-on-amur',
    'Благовещенск' => 'blagoveshchensk',
    'Биробиджан' => 'birobidzhan',
    'Южно-Сахалинск' => 'yuzhno-sakhalinsk',
    'Якутск' => 'yakutsk',
    'Белогорск' => 'belogorsk',
    'Свободный' => 'svobodny',
    'Котлас' => 'kotlas',
    'Ахтубинск' => 'akhtubinsk',
    'Губкин' => 'gubkin',
    'Шебекино' => 'shebekino',
    'Клинцы' => 'klintsy',
    'Новозыбков' => 'novozybkov',
    'Ковров' => 'kovrov',
    'Муром' => 'murom',
    'Александров' => 'aleksandrov',
    'Гусь-Хрустальный' => 'gus-khrustalnyy',
    'Михайловка' => 'mikhaylovka',
    'Урюпинск' => 'uryupinsk',
    'Нововоронеж' => 'novovoronezh',
    'Кинешма' => 'kineshma',
    'Шуя' => 'shuya',
    'Усолье-Сибирское' => 'usolye-sibirskoe',
    'Шелехов' => 'shelekhov',
    'Саянск' => 'sayansk',
    'Зима' => 'zima',
    'Нижнеудинск' => 'nizhneudinsk',
    'Тулун' => 'tulun',
    'Тайшет' => 'tayshet',
    'Черемхово' => 'cheremkhovo',
    'Советск' => 'sovetsk',
    'Малоярославец' => 'maloyaroslavets',
    'Ленинск-Кузнецкий' => 'leninsk-kuznetsky',
    'Киселёвск' => 'kiselevsk',
    'Юрга' => 'yurga',
    'Белово' => 'belovo',
    'Анжеро-Судженск' => 'anzhero-sudzhensk',
    'Осинники' => 'osinniki',
    'Мыски' => 'myski',
    'Киров' => 'kirov',
    'Кирово-Чепецк' => 'kirovo-chepetsk',
    'Слободской' => 'slobodskoy',
    'Вятские Поляны' => 'vyatskiye-polyany',
    'Шадринск' => 'shadrinsk',
    'Сосновый Бор' => 'sosnovyy-bor',
    'Кудрово' => 'kudrovo',
    'Елец' => 'yelets',
    'Грязи' => 'gryazi',
    'Магадан' => 'magadan',
    'Североморск' => 'severomorsk',
    'Саров' => 'sarov',
    'Кстово' => 'kstovo',
    'Павлово' => 'pavlovo',
    'Старая Русса' => 'staraya-russa',
    'Куйбышев' => 'kuybyshev',
    'Соль-Илецк' => 'sol-ilets',
    'Сорочинск' => 'sorochinsk',
    'Новотроицк' => 'novotrotsk',
    'Бугуруслан' => 'buguruslan',
    'Бузулук' => 'buzuluk',
    'Ливны' => 'livny',
    'Кузнецк' => 'kuznetsk',
    'Заречный' => 'zarechny',
    'Азов' => 'azov',
    'Гуково' => 'gukovo',
    'Каменск-Шахтинский' => 'kamensk-shakhtinsky',
    'Донецк' => 'donetsk',
    'Чапаевск' => 'chapayevsk',
    'Жигулёвск' => 'zhigulevsk',
    'Отрадный' => 'otradny',
    'Балашов' => 'balashov',
    'Вольск' => 'volsk',
    'Пугачёв' => 'pugachev',
    'Ртищево' => 'rtishchevo',
    'Реж' => 'rezh',
    'Сухой Лог' => 'sukhoi-log',
    'Богданович' => 'bogdanovich',
    'Полевской' => 'polevskoy',
    'Ревда' => 'revda',
    'Вязьма' => 'vyazma',
    'Сафоново' => 'safonovo',
    'Рославль' => 'roslavl',
    'Ярцево' => 'yartsevo',
    'Мичуринск' => 'michurinsk',
    'Рассказово' => 'rasskazovo',
    'Моршанск' => 'morshansk',
    'Ржев' => 'rzhev',
    'Вышний Волочёк' => 'vyshniy-volochek',
    'Торжок' => 'torzhok',
    'Стрежевой' => 'strezhvoy',
    'Щёкино' => 'shchyokino',
    'Алексин' => 'aleksin',
    'Донской' => 'donskoy',
    'Узловая' => 'uzlovaya',
    'Тобольск' => 'tobolsk',
    'Ишим' => 'ishim',
    'Ялуторовск' => 'yalutorovsk',
    'Снежинск' => 'snezhinsk',
    'Сатка' => 'satka',
    'Чебаркуль' => 'chebarkul',
    'Рыбинск' => 'rybinsk',
    'Переславль-Залесский' => 'pereslavl-zalesskiy',
    'Уфа' => 'ufa',
    'Нальчик' => 'nalchik',
    'Нижнекамск' => 'nizhnekamsk',
    'Люберцы' => 'lyubercy',
    'Абакан' => 'abakan',
    'Петропавловск-Камчатский' => 'petropavlovsk-kamchatskij',
    'Альметьевск' => 'almetevsk',
    'Хасавюрт' => 'hasavyurt',
    'Керчь' => 'kerch',
    'Салават' => 'salavat',
    'Нефтекамск' => 'neftekamsk',
    'Кисловодск' => 'kislovodsk',
    'Кызыл' => 'kyzyl',
    'Дербент' => 'derbent',
    'Нефтеюганск' => 'nefteyugansk',
    'Назрань' => 'nazran',
    'Каспийск' => 'kaspijsk',
    'Новочебоксарск' => 'novocheboksarsk',
    'Ессентуки' => 'essentuki',
    'Невинномысск' => 'nevinnomyssk',
    'Октябрьский' => 'oktyabrskij',
    'Михайловск' => 'mihajlovsk',
    'Черкесск' => 'cherkessk',
    'Артём' => 'artyom',
    'Евпатория' => 'evpatoriya',
    'Ханты-Мансийск' => 'hanty-mansijsk',
    'Новый Уренгой' => 'novyj-urengoj',
    'Элиста' => 'ehlista',
    'Ноябрьск' => 'noyabrsk',
    'Зеленодольск' => 'zelenodolsk',
    'Воткинск' => 'votkinsk',
    'Сарапул' => 'sarapul',
    'Глазов' => 'glazov',
    'Бугульма' => 'bugulma',
    'Ухта' => 'uhta',
    'Озёрск' => 'ozyorsk',
    'Черногорск' => 'chernogorsk',
    'Ялта' => 'yalta',
    'Елабуга' => 'elabuga',
    'Новоалтайск' => 'novoaltajsk',
    'Минеральные Воды' => 'mineralnye-vody',
    'Туймазы' => 'tujmazy',
    'Сертолово' => 'sertolovo',
    'Буйнакск' => 'bujnaksk',
    'Феодосия' => 'feodosiya',
    'Горно-Алтайск' => 'gorno-altajsk',
    'Белорецк' => 'beloreck',
    'Гудермес' => 'gudermes',
    'Ишимбай' => 'ishimbaj',
    'Урус-Мартан' => 'urus-martan',
    'Георгиевск' => 'georgievsk',
    'Нягань' => 'nyagan',
    'Сунжа' => 'sunzha',
    'Когалым' => 'kogalym',
    'Лениногорск' => 'leninogorsk',
    'Прохладный' => 'prohladnyj',
    'Белебей' => 'belebej',
    'Чистополь' => 'chistopol',
    'Будённовск' => 'budyonnovsk',
    'Кумертау' => 'kumertau',
    'Сальск' => 'salsk',
    'Асбест' => 'asbest',
    'Воркута' => 'vorkuta',
    'Сибай' => 'sibaj',
    'Мелеуз' => 'meleuz',
    'Избербаш' => 'izberbash',
    'Краснотурьинск' => 'krasnoturinsk',
    'Тихорецк' => 'tihoreck',
    'Шали' => 'shali',
    'Зеленогорск' => 'zelenogorsk',
    'Нерюнгри' => 'neryungri',
    'Волжск' => 'volzhsk',
    'Мегион' => 'megion',
    'Тимашёвск' => 'timashyovsk',
    'Краснокаменск' => 'krasnokamensk',
];

// Получаем домен и поддомен
$domain = $_SERVER['HTTP_HOST'];
$host_array = explode('.', $_SERVER['HTTP_HOST']);

$subdomain = null;
if (count($host_array) > 2) {
    $domain = $host_array[count($host_array) - 2] . '.' . $host_array[count($host_array) - 1];

    if ($find_context_prefix) {
        $subdomain = str_replace($find_context_prefix, '', $host_array[0]);
    } else {
        $subdomain = $host_array[0];
    }
}

// Получаем куки - проверяем какой город выбран сейчас
$cookie_city = isset($_COOKIE[KEY]) ? $_COOKIE[KEY] : null;
// Получаем сессию - проверяем какой город был прошлым значением
$session_city = isset($_SESSION[KEY]) ? $_SESSION[KEY] : null;

// Генерировать редирект ?
$generate_redirect = false;

// Если ранее выбранный город не совпадает с текущим -> редирект
if ($cookie_city !== $session_city) $generate_redirect = true;

// Если значения заполнены и:
if (isset($cookie_city) && isset($session_city)) {
    // Поддомен есть:
    if (isset($subdomain)) {
        // Не соответсвует выбранному городу -> редирект
        if (isset($cities[$cookie_city]) && $cities[$cookie_city] !== $subdomain) {
            $generate_redirect = true;
        }
    }
    // Нет поддомена -> редирект
    else {
        $generate_redirect = true;
    }
}

if ($generate_redirect === false) return;

// Записываем в сессию текущий город для будущей проверки
$_SESSION[KEY] = $cookie_city;

// Определяем поддомен для выбранного города
$new_subdomain = "";
if ($cookie_city) {

    $generate_url = false;
    if (isset($cities[$cookie_city])) $generate_url = true;
    if ($modx->context->key === DEFAULT_CONTEXT && $cookie_city === DEFAULT_VALUE) $generate_url = false;

    if ($generate_url) {
        $new_subdomain =  $find_context_prefix . $cities[$cookie_city] . '.';
    } else {
        setcookie(
            KEY,
            "",
            time() - 3600,
            "/",
            "." . $domain
        );
        unset($_SESSION[KEY]);
    }
}

$url = 'https://' . $new_subdomain . $domain . $_SERVER['REQUEST_URI'];

header("Location: $url");
exit;
